---
language: python
python: '2.7'
sudo: false
addons:
  apt:
    packages:
    - python-pip
jobs:
  include:
  - stage: test
    install:
    - pip install ansible
    - ansible --version
    script:
    - "./test.sh"
  - stage: package:deploy
    install:
    - gem install fpm
    script:
    - fpm -s dir -x providers -x .git -t deb -n ansible-make -v $(cat VERSION) ansible-make=/usr/local/bin/
      Makefile=/opt/ansible/ pass.sh=/opt/ansible/
    deploy:
      provider: releases
      api_key:
        secure: jl+DNWPR1ig3n6yBVkW3rWXm5VqVZVQSHiibPv9KHUXsmZKoNrTK7EKx4mOaqWvRWFTgmlq+EaAsy+ue/yS0dL5Bk0swRCn0lcRBHt5rBMyJ72tLV1V1vXg24n8kcEAi2J4C0KSnTOFqtwf4KMHyDv5BlGUkpX/eMuTukOZbfbdqHBMO2k++vWIIWmvMa+ZlykYqj1YGtRvDnhSVSPI5kRPxFiENZif3u1AH2r6SCQX2Hz/2mkltaNqoa99LjS4ARI8ykHyx+NBjJqD3s31NhsNNow/mKCXr29oNZECEnBSfIum414A1WzmzQ92EOc/AdB3cQQCdwR+VmbtejtETWK050oSD/Bl/i3ixnR/TusbYB+M0yjxvr1ugnMoCI6wZmH8qdYLmytQRzOZ12V8jrvfNRJ5M3kHjQSBOFRli2pclokurm8cjraf+BVeaeDJ/CMGNgBAQpw8OGOTcYCWnkIXwIicis0/agggaQG4IzDfXC5SDSUH+2wpeiNppjVoU7O6p4lJwnyLq36+2jPo9xIj7FnqPv2wTGMgYQjHSADfnzZJfNvJp5bH4ylNNzmZWbCo8tf4j2LFnj+6DvYrsWyMZk0PwUYJirOI43s1jETtwb+U1r57D5ugbz0MM0GjFyewIADvXQtMgoWH0jQjvx28+6zJN8SwOMcwXJAPe8P8=
      file_glob: true
      file: ansible-make_*_amd64.deb
      skip_cleanup: true
      on:
        repo: paulRbr/ansible-makefile
        tags: true
